version: "3.1"

services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: always
    networks:
      - mediarr
    ports:
      - "7878:7878"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    volumes:
      - ${RUNTIME_PATH}/radarr:/config
      - ${RUNTIME_PATH}/transmission/completed:/downloads
      - ${MEDIA_PATH}/Movies:/movies

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: always
    networks:
      - mediarr
    ports:
      - "8989:8989"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    volumes:
      - ${RUNTIME_PATH}/sonarr:/config
      - ${MEDIA_PATH}/TV-Shows:/tv
      - ${RUNTIME_PATH}/transmission/completed:/downloads

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    networks:
      - mediarr
    ports:
      - "9117:9117"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    volumes:
      - ${RUNTIME_PATH}/jackett:/config
      - ${RUNTIME_PATH}/jackett/downloads:/downloads

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    restart: always
    networks:
      - mediarr
    ports:
      - "9091:9091"
    environment:
      - OPENVPN_PROVIDER=${VPN_PROVIDER}
      - OPENVPN_CONFIG=${VPN_CONFIG}
      - OPENVPN_USERNAME=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - OPENVPN_OPTS="--inactive 3600 --ping 10 --ping-exit 60"
    volumes:
      - ${RUNTIME_PATH}/transmission:/data
      #- /etc/localtime:/etc/localtime:ro

  plex:
    image: timhaak/plex
    container_name: plex
    restart: always
    networks:
      - mediarr
    ports:
      - "32400:32400"
      - "1900:1900"
      - "3005:3005"
      - "5353:5353"
      - "8324:8324"
      - "32410:32410"
      - "32412:32412"
      - "32413:32413"
      - "32414:32414"
      - "32469:32469"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Stockholm
    volumes:
      - ${RUNTIME_PATH}/plex:/config
      - ${MEDIA_PATH}:/data

networks:
  mediarr:
    driver: bridge
